### ISSUE TITLE
plugin potentially recalculates fallback prices of customer group

### ISSUE THREAD

**Issue by marcnoller** [shopwareLabs/SwagTax#16]
In the configuration it is possible to enable the recalculation of (net) prices only for given customer groups.

Let's take the following scenario:
* EK shall be recalculated
* H shall _not_ be recalculated

Now, in H prices have _not_ been explicitly set for all articles. Hence, there are articles that use EK as fallback price.

The issue is, that the plugin currently would recalculate alle EK prices and thus implicitly recalculate prices for H.

If an article has not set a price in H, the plugin should copy the price of EK to H before starting the recalculation.

**Comment by PaddyS** [comment]
Hey @marcnoller,

thank you very much for your feedback! 💙 

We've already had an internal discussion about the case you've mentioned.
While we totally understand the case, we do not think this is a good solution. There are customers who rely heavily on price inheritance.
They probably wouldn't even notice the "removed inheritance" on some products and would therefore run into new problems.

We'll add another information text for this case though!

**Comment by marcnoller** [comment]
Hey @PaddyS, thanks for your feedback and adding the info!
