### ISSUE TITLE
New Tax Ids

### ISSUE THREAD

**Issue by anewarray** [shopwareLabs/SwagTax#23]
Why does the plugin generate new Ids? Some softwares uses the default 1 & 4 id for tax.
At least for the reset at the end of the year it would be helpful if the plugin would use the old ids.

My suggestion is to extend the wizards tax-matching with drop-down of the tax-table and the option just to change the rate without the ID.

**Comment by mitelg** [comment]
external Software relying on internal IDs of Shopware? that sounds like a bad idea :see_no_evil:

**Comment by anewarray** [comment]
Sure.  But beside that we will have "duplicate entries" in Jan 2021, because the plugin doesn't use the original tax-ids for the reset.

**Comment by shyim** [comment]
It has other technical reasons why we create a new tax.

When you modify the current tax. It will break the old already taken orders in the system when you edit them

**Comment by PaddyS** [comment]
Hey @anewarray,

thanks for your issue.
Don't you worry, we've got you covered "on the way back to 19%".
There will be a possiblity to map to an existing tax instead of creating a new one. This will be added before you'll actually need it at the end of the year. :-)
