### ISSUE TITLE
"name" missing from composer.json

### ISSUE THREAD

**Issue by mariofischer** [shopwareLabs/SwagTax#27]
When installing the plugin (via composer and/or via plugin manager) and running "composer update" afterwards, the following error occurs:
                                                                                                                                             
```
  [UnexpectedValueException]                                                                                                                 
  Unknown package has no name defined ({"require-dev":{"frosh\/shopware-classic-phpunit-bridge":"dev-master","phpunit\/phpunit":"^5"},"dist":{"type":"path","url":".\/custom\/plugins\/SwagTax","reference":"cf35296ed01f64fe41051318efd1c492ad7d36d7"},"transport-options":{"relative":true},"version":"dev-Development"}).
```

I assume this can be fixed by adding the following line to /composer.json:

`"name": "shopwarelabs/swagtax"`

**Comment by mitelg** [comment]
you are right, that should do the trick.👍
 what about a PR? 😉

**Comment by mariofischer** [comment]
Done 😄
